// Build the per-series copy deliverables from one source of truth:
//   content/series-kits.md   hooks, captions, YouTube titles, WhatsApp lines per series
//   ads/meta-ads.csv         Meta primary text / headline / description variants
//   ads/google-ads.csv       Google headlines, long headlines, descriptions
// Inputs: data/catalog.json (live synopses), data/hooks.json, data/series-copy.json.
// Fails if any ad line breaks a platform character limit.
//
//   node marketing/templates/copy.mjs
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, slugify } from './lib.mjs';

const M = (p) => path.join(ROOT, 'marketing', p);
const catalog = JSON.parse(fs.readFileSync(M('data/catalog.json'), 'utf8'));
const hooks = JSON.parse(fs.readFileSync(M('data/hooks.json'), 'utf8'));
const extra = JSON.parse(fs.readFileSync(M('data/series-copy.json'), 'utf8'));

// Series without key art yet: hooks only, creatives pending.
const NO_ART = {
  shanghai: { title: 'Love in Shanghai', hook: 'सड़क की वायलिनिस्ट… और एक अरबपति वारिस।', roman: 'Ek violinist, ek billionaire… aur ek chhupi shaadi.' },
  mafiaking: { title: "Mafia King's Heart", hook: 'उसे गिराने गई थी… वो पहले दिन से जानता था।', roman: 'Undercover gayi thi… woh pehle din se jaanta tha.' },
  palace: { title: 'Imperial Palace Secrets', hook: 'सम्राट को ज़हर से बचाया… और देशद्रोही कहलाई।', roman: 'Samraat ko bachaya… aur gaddar kehlaayi.' },
};

const plain = (h) => h.replace(/<br>/g, ' ').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const seg = new Intl.Segmenter('hi', { granularity: 'grapheme' });
const len = (s) => [...seg.segment(s)].length;
const bySlug = Object.fromEntries(catalog.map((s) => [slugify(s.title), s]));
const find = (title) => bySlug[slugify(title)];

const LIMITS = { metaPrimary: 125, metaHeadline: 40, metaDescription: 30, gHeadline: 30, gDgHeadline: 40, gLong: 90, gDesc: 90 };
const errors = [];
const ok = (where, s, max) => (len(s) <= max ? true : (errors.push(`${where}: ${len(s)} > ${max} — "${s}"`), false));

const FORMULA = { h01: 'Betrayal reveal', h02: 'Hidden identity', h03: 'Price of a miracle', h04: 'Revenge vow', h05: 'Forbidden choice', h06: 'Cold open on action', h07: 'Question to camera', h08: 'Countdown / stakes' };
const SHORT = { "The Billionaire's Revenge": "Billionaire's Revenge", "The Mafia Lord's Bride": "Mafia Lord's Bride", 'Pishachini: The Healer': 'Pishachini' };
const csv = (rows) => rows.map((r) => r.map((v) => `"${String(v ?? '').replace(/"/g, '""')}"`).join(',')).join('\n') + '\n';

const meta = [['series', 'alias', 'status', 'campaign', 'ad_name', 'language', 'primary_text', 'headline', 'description', 'cta_button', 'website_url', 'url_parameters', 'creative_9x16', 'creative_4x5', 'creative_1x1']];
const google = [['series', 'alias', 'status', 'use_in', 'asset_type', 'text', 'chars', 'final_url']];
let md = `# Series kits: hooks, captions and copy for every live series

Generated by \`templates/copy.mjs\` from \`data/catalog.json\` (live synopses), \`data/hooks.json\` and
\`data/series-copy.json\`. Edit the data files and re-run; don't hand-edit this file.

**Status key.** ✅ ready to promote · ⚠️ tagged \`__demo__\` in the live catalog: watch Episode 1 before any spend ·
🖼️ no key art yet: hooks only, creatives pending.

Every caption keeps the AI line, and every link uses \`thegulel.com/go/{alias}\` plus the UTM rules in \`05-tracking-and-funnel.md\` §3.

`;

for (const h of hooks) {
  const s = find(h.title);
  const x = extra[h.alias];
  if (!s || !x) throw new Error(`missing catalog or copy data for ${h.alias}`);
  const status = h.verify ? '⚠️ verify' : '✅ ready';
  const hookPlain = plain(h.hookHi);
  const short = SHORT[h.title] ?? h.title;
  const go = `thegulel.com/go/${h.alias}`;

  // ── Meta variants (Devanagari / Hinglish / English) ──
  const variants = [
    ['hi', `${hookPlain} ${x.emoji}\nEpisode 1 फ्री देखें। आगे के एपिसोड coins या VIP से।`],
    ['hinglish', `${x.roman} ${x.emoji}\nEpisode 1 FREE on Gulel. Ep 2+ with coins or VIP.`],
    ['en', `${h.hookEn}\nEpisode 1 free on Gulel · Ep 2+ with coins or VIP.`],
  ];
  const headline = `${short} · Episode 1 FREE`;
  const description = '2-min episodes · AI Original';
  ok(`${h.alias} meta headline`, headline, LIMITS.metaHeadline);
  for (const [lang, primary] of variants) {
    ok(`${h.alias} meta ${lang}`, primary, LIMITS.metaPrimary);
    meta.push([h.title, h.alias, status, `202610_pilot-test_${h.alias}`, `${h.alias}_${x.hooks[0][0]}_${lang}`, lang, primary, headline, description, 'WATCH_MORE',
      `https://${go}`, 'utm_source={{site_source_name}}&utm_medium=paid_social&utm_campaign={{campaign.name}}&utm_term={{adset.name}}&utm_content={{ad.name}}',
      `marketing/assets/ads/${h.alias}/meta-9x16.jpg`, `marketing/assets/ads/${h.alias}/meta-4x5.jpg`, `marketing/assets/ads/${h.alias}/meta-1x1.jpg`]);
  }

  // ── Google assets ──
  const url = `https://${go}?utm_source=google&utm_medium=demand_gen&utm_campaign=202610_pilot-test_${h.alias}`;
  const gHeads = [h.title, 'Episode 1 FREE on Gulel', ...x.hooks.filter(([, t]) => !t.startsWith('(')).map(([, t]) => t)].filter((t) => len(t) <= LIMITS.gHeadline).slice(0, 5);
  const dg = [x.roman, h.hookEn].filter((t) => len(t) <= LIMITS.gDgHeadline);
  const longH = len(`${h.hookEn} Watch Episode 1 free.`) <= LIMITS.gLong ? `${h.hookEn} Watch Episode 1 free.` : h.hookEn;
  const descs = ['Watch Episode 1 free on Gulel. 2-minute Hindi episodes. Ep 2+ with coins or VIP.', h.hookEn];
  gHeads.forEach((t) => google.push([h.title, h.alias, status, 'Search · App · Demand Gen', 'headline (≤30)', t, len(t), url]));
  dg.forEach((t) => google.push([h.title, h.alias, status, 'Demand Gen', 'headline (≤40)', t, len(t), url]));
  ok(`${h.alias} google long`, longH, LIMITS.gLong);
  google.push([h.title, h.alias, status, 'Demand Gen · PMax', 'long headline (≤90)', longH, len(longH), url]);
  descs.forEach((t) => { ok(`${h.alias} google desc`, t, LIMITS.gDesc); google.push([h.title, h.alias, status, 'Search · App · Demand Gen', 'description (≤90)', t, len(t), url]); });

  // ── Markdown kit ──
  const ep1 = s.episodes.find((e) => e.number === 1);
  md += `
---

## ${h.title}${s.titleHi ? ` · ${s.titleHi}` : ''}  ${status}

\`${go}\` · ${s.genre} · ${s.totalEpisodes} episodes (Ep 1 free, ${ep1?.duration ?? '?'} s) · ${s.coinPrice} coins/episode

> ${s.description}

**Ad hook:** ${hookPlain} — *${h.hookEn}*

| Cut | Hook | First-frame text (≤ 7 words) |
|---|---|---|
${x.hooks.map(([id, t], i) => `| ${i + 1} | \`${id}\` ${FORMULA[id]} | ${t} |`).join('\n')}

**Instagram / Facebook caption**
\`\`\`
${hookPlain} ${x.emoji}
${x.roman}
Episode 1 फ्री 👉 link in bio · ${go}
${x.tags}
AI-generated Gulel Original · एआई द्वारा निर्मित
\`\`\`
**YouTube title (Episode 1 upload):** \`${h.title} | Episode 1 | ${x.hooks[0][1].replace(/^\(.*\)\s*/, '')} | Gulel Original\`
**YouTube Short title:** \`${hookPlain.split('…')[0]}… 😱 #${h.alias} #shorts\`
**WhatsApp Channel:** \`🔔 ${hookPlain} — Episode 1 फ्री 👉 ${go}?utm_source=whatsapp&utm_medium=whatsapp_channel&utm_campaign=202610_${h.alias}\`
**Creatives:** \`assets/ads/${h.alias}/\` (meta-9x16, meta-4x5, meta-1x1, google-1200x628, google-1200x1200, google-960x1200, endcard-1080x1920, youtube-thumb-1280x720)
`;
}

md += `
---

## Series without key art (🖼️ hooks only)

Their thumbnails are video frame grabs. Commission a 9:16 poster (the same Nano Banana brief as the rest of the slate), add it to
\`public/thumbnails/\`, add an entry to \`data/hooks.json\` and re-render.

| Series | Alias | Synopsis | Hook | Hinglish |
|---|---|---|---|---|
${Object.entries(NO_ART).map(([alias, n]) => { const s = find(n.title); return `| ${n.title} | \`${alias}\` | ${s?.description ?? ''} | ${n.hook} | ${n.roman} |`; }).join('\n')}
`;

if (errors.length) {
  console.error(`✗ ${errors.length} lines over the limit:\n  ` + errors.join('\n  '));
  process.exit(1);
}
fs.mkdirSync(M('ads'), { recursive: true });
fs.mkdirSync(M('content'), { recursive: true });
fs.writeFileSync(M('content/series-kits.md'), md);
fs.writeFileSync(M('ads/meta-ads.csv'), '﻿' + csv(meta)); // BOM so Sheets/Excel read Devanagari as UTF-8
fs.writeFileSync(M('ads/google-ads.csv'), '﻿' + csv(google));
console.log(`✓ ${hooks.length} series kits · ${meta.length - 1} Meta ads · ${google.length - 1} Google assets, all within limits`);
